# Site settings
title: "Weijie HUANG"
email: tracy4816@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://koalagreener.github.io"
title_description: "I am a postgraduate student studying in UCL."
title_image: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/7/005/082/349/2038358.jpg"
google_analytics: "UA-20365477-4"
disqus_account: None
github_repository: https://github.com/koalaGreener
addthis_id: None
post_limit: 5

# Social usernames/URLs
twitter_username: GreenerGooner
github_username:  koalaGreener
linkedin_link: https://www.linkedin.com/in/WeijieHuangUCL
google_plus_link: None
stackoverflow_link: None

# Footer
footer_left: "<i class=\"fa fa-heart\"></i>"
footer_right: "Support by <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
